//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amigos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int TotalPages { get; set; }
        public string ISBN { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public int AuthorId { get; set; }
        public int PublisherId { get; set; }
        public int ImageId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Image Image { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
